import { Job } from './job.model';

export const MOCK_JOBS: Job[] = [
  {
    id: 'n1',
    title: 'Senior Angular Developer',
    company: 'Infosys',
    location: 'Bengaluru, Karnataka',
    salary: '₹18 – 28 LPA',
    platform: 'naukri',
    url: 'https://www.naukri.com/job-listings-senior-angular-developer',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'senior',
    skills: ['Angular', 'TypeScript', 'RxJS', 'NgRx'],
    description: 'Build large-scale enterprise Angular applications with microservices backend.',
  },
  {
    id: 'n2',
    title: 'Frontend Engineer – React/Angular',
    company: 'Wipro Technologies',
    location: 'Hyderabad, Telangana',
    salary: '₹12 – 20 LPA',
    platform: 'naukri',
    url: 'https://www.naukri.com/job-listings-frontend-engineer',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'mid',
    skills: ['Angular', 'React', 'JavaScript', 'CSS'],
    description: 'Develop responsive web interfaces for banking domain clients.',
  },
  {
    id: 'n3',
    title: 'Full Stack Developer (Angular + Node)',
    company: 'TCS',
    location: 'Pune, Maharashtra',
    salary: '₹10 – 18 LPA',
    platform: 'naukri',
    url: 'https://www.naukri.com/job-listings-fullstack-developer',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'mid',
    skills: ['Angular', 'Node.js', 'MongoDB', 'Express'],
    description: 'Work on full stack product development for healthcare platform.',
  },
  {
    id: 'n4',
    title: 'UI Developer (Angular)',
    company: 'HCL Technologies',
    location: 'Chennai, Tamil Nadu',
    salary: '₹6 – 12 LPA',
    platform: 'naukri',
    url: 'https://www.naukri.com/job-listings-ui-developer',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'junior',
    skills: ['Angular', 'Bootstrap', 'SCSS', 'HTML5'],
    description: 'Build pixel-perfect UI components for enterprise dashboards.',
  },
  {
    id: 'n5',
    title: 'Lead Frontend Architect',
    company: 'Cognizant',
    location: 'Mumbai, Maharashtra',
    salary: '₹30 – 45 LPA',
    platform: 'naukri',
    url: 'https://www.naukri.com/job-listings-lead-architect',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'lead',
    skills: ['Angular', 'Micro Frontends', 'Nx', 'Module Federation'],
    description: 'Architect and govern micro-frontend ecosystem for retail banking.',
  },
  {
    id: 'li1',
    title: 'Angular Software Engineer',
    company: 'Google',
    location: 'Bengaluru, Karnataka',
    salary: '₹40 – 60 LPA',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/jobs/view/angular-software-engineer-google',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'senior',
    skills: ['Angular', 'TypeScript', 'Go', 'gRPC'],
    description: 'Join the Angular team and shape the future of the framework.',
  },
  {
    id: 'li2',
    title: 'Remote Frontend Developer',
    company: 'Razorpay',
    location: 'Remote',
    salary: '₹20 – 35 LPA',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/jobs/view/frontend-developer-razorpay',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    type: 'remote',
    experience: 'mid',
    skills: ['Angular', 'Vue.js', 'Payment APIs', 'TypeScript'],
    description: 'Build checkout and payment experiences for millions of merchants.',
  },
  {
    id: 'li3',
    title: 'Junior Angular Developer',
    company: 'Zomato',
    location: 'Gurugram, Haryana',
    salary: '₹8 – 14 LPA',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/jobs/view/angular-developer-zomato',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'junior',
    skills: ['Angular', 'RxJS', 'REST APIs', 'Git'],
    description: 'Work on consumer-facing food ordering web application.',
  },
  {
    id: 'li4',
    title: 'Staff Frontend Engineer',
    company: 'Flipkart',
    location: 'Bengaluru, Karnataka',
    salary: '₹45 – 70 LPA',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/jobs/view/staff-engineer-flipkart',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'lead',
    skills: ['Angular', 'React', 'Performance', 'Web Vitals'],
    description: 'Drive web performance and architecture for e-commerce at massive scale.',
  },
  {
    id: 'li5',
    title: 'Contract Angular Consultant',
    company: 'Accenture',
    location: 'Hyderabad, Telangana',
    salary: '₹15 – 25 LPA',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/jobs/view/angular-consultant-accenture',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    type: 'contract',
    experience: 'senior',
    skills: ['Angular', 'Azure', 'CI/CD', 'Agile'],
    description: '6-month contract for financial services digital transformation project.',
  },
  {
    id: 'li6',
    title: 'Frontend Developer Intern',
    company: 'PhonePe',
    location: 'Bengaluru, Karnataka',
    salary: '₹40,000/month',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/jobs/view/intern-phonepe',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    type: 'internship',
    experience: 'fresher',
    skills: ['Angular', 'JavaScript', 'HTML', 'CSS'],
    description: 'Six-month internship working on fintech web products.',
  },
  {
    id: 'in1',
    title: 'Angular Developer',
    company: 'Persistent Systems',
    location: 'Pune, Maharashtra',
    salary: '$80,000 – $100,000/yr',
    platform: 'indeed',
    url: 'https://in.indeed.com/jobs/angular-developer-persistent',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'mid',
    skills: ['Angular', 'TypeScript', 'REST', 'Jenkins'],
    description: 'Develop client web apps for US healthcare customers.',
  },
  {
    id: 'in2',
    title: 'Remote Angular / React Developer',
    company: 'Mphasis',
    location: 'Remote',
    salary: '₹14 – 22 LPA',
    platform: 'indeed',
    url: 'https://in.indeed.com/jobs/angular-react-mphasis',
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    type: 'remote',
    experience: 'mid',
    skills: ['Angular', 'React', 'GraphQL', 'AWS'],
    description: 'Remote position for cloud-native SaaS platform.',
  },
  {
    id: 'in3',
    title: 'Fresher – Web Developer (Angular)',
    company: 'Tech Mahindra',
    location: 'Noida, Uttar Pradesh',
    salary: '₹4 – 7 LPA',
    platform: 'indeed',
    url: 'https://in.indeed.com/jobs/fresher-angular-techmahindra',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'fresher',
    skills: ['Angular', 'JavaScript', 'HTML5', 'Bootstrap'],
    description: 'Entry-level opportunity for recent graduates in IT services.',
  },
  {
    id: 'in4',
    title: 'Senior UI / Angular Specialist',
    company: 'Oracle India',
    location: 'Bengaluru, Karnataka',
    salary: '₹22 – 38 LPA',
    platform: 'indeed',
    url: 'https://in.indeed.com/jobs/senior-angular-oracle',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    type: 'full-time',
    experience: 'senior',
    skills: ['Angular', 'Oracle JET', 'TypeScript', 'REST'],
    description: 'Build next-generation Oracle cloud product interfaces.',
  },
  {
    id: 'in5',
    title: 'Part-time Angular Trainer / Developer',
    company: 'NIIT Technologies',
    location: 'Delhi, NCR',
    salary: '₹6 – 10 LPA',
    platform: 'indeed',
    url: 'https://in.indeed.com/jobs/angular-trainer-niit',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    type: 'part-time',
    experience: 'senior',
    skills: ['Angular', 'Training', 'TypeScript', 'Git'],
    description: 'Part-time role combining development work with training batch delivery.',
  },
];
