import type { TreeSpecies } from './models';

export const TREE_SPECIES: TreeSpecies[] = [
  {
    id: 'oak',
    commonName: 'Oak',
    scientificName: 'Quercus robur',
    co2PerYear: 22,
    co2YoungMultiplier: 0.3,
    growthRate: 'slow',
    maxHeightM: 20,
    lifespanYears: 500,
    nativeRegion: 'Europe, North America',
    careTips: 'Full sun, well-drained soil. Water deeply but infrequently. Prune in late winter.',
    category: 'deciduous',
    icon: '🌳',
  },
  {
    id: 'maple',
    commonName: 'Maple',
    scientificName: 'Acer saccharum',
    co2PerYear: 18,
    co2YoungMultiplier: 0.35,
    growthRate: 'medium',
    maxHeightM: 25,
    lifespanYears: 300,
    nativeRegion: 'North America',
    careTips: 'Full sun to partial shade. Prefers moist, well-drained soil. Avoid compacted soil.',
    category: 'deciduous',
    icon: '🍁',
  },
  {
    id: 'pine',
    commonName: 'Pine',
    scientificName: 'Pinus sylvestris',
    co2PerYear: 20,
    co2YoungMultiplier: 0.4,
    growthRate: 'medium',
    maxHeightM: 30,
    lifespanYears: 200,
    nativeRegion: 'Europe, Asia',
    careTips: 'Full sun. Well-drained, sandy or loamy soil. Drought tolerant once established.',
    category: 'evergreen',
    icon: '🌲',
  },
  {
    id: 'neem',
    commonName: 'Neem',
    scientificName: 'Azadirachta indica',
    co2PerYear: 25,
    co2YoungMultiplier: 0.45,
    growthRate: 'fast',
    maxHeightM: 20,
    lifespanYears: 150,
    nativeRegion: 'South Asia',
    careTips: 'Full sun, tolerates poor soil. Water regularly until established. Highly drought resistant.',
    category: 'evergreen',
    icon: '🌿',
  },
  {
    id: 'mango',
    commonName: 'Mango',
    scientificName: 'Mangifera indica',
    co2PerYear: 15,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 15,
    lifespanYears: 100,
    nativeRegion: 'South Asia',
    careTips: 'Full sun, well-drained soil. Water regularly. Fertilize twice a year.',
    category: 'fruit',
    icon: '🥭',
  },
  {
    id: 'apple',
    commonName: 'Apple',
    scientificName: 'Malus domestica',
    co2PerYear: 12,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 10,
    lifespanYears: 80,
    nativeRegion: 'Central Asia',
    careTips: 'Full sun, well-drained soil. Prune annually. Requires cross-pollination.',
    category: 'fruit',
    icon: '🍎',
  },
  {
    id: 'cherry',
    commonName: 'Cherry',
    scientificName: 'Prunus avium',
    co2PerYear: 10,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 12,
    lifespanYears: 60,
    nativeRegion: 'Europe, Western Asia',
    careTips: 'Full sun, well-drained fertile soil. Water regularly, especially in dry spells.',
    category: 'fruit',
    icon: '🍒',
  },
  {
    id: 'banyan',
    commonName: 'Banyan',
    scientificName: 'Ficus benghalensis',
    co2PerYear: 30,
    co2YoungMultiplier: 0.25,
    growthRate: 'fast',
    maxHeightM: 30,
    lifespanYears: 500,
    nativeRegion: 'South Asia',
    careTips: 'Full sun, moist soil. Very large tree – needs wide open space. Aerial roots spread widely.',
    category: 'deciduous',
    icon: '🌴',
  },
  {
    id: 'eucalyptus',
    commonName: 'Eucalyptus',
    scientificName: 'Eucalyptus globulus',
    co2PerYear: 35,
    co2YoungMultiplier: 0.5,
    growthRate: 'fast',
    maxHeightM: 55,
    lifespanYears: 100,
    nativeRegion: 'Australia',
    careTips: 'Full sun, drought tolerant. Fast grower – plant away from structures.',
    category: 'evergreen',
    icon: '🌿',
  },
  {
    id: 'coconut',
    commonName: 'Coconut Palm',
    scientificName: 'Cocos nucifera',
    co2PerYear: 8,
    co2YoungMultiplier: 0.2,
    growthRate: 'medium',
    maxHeightM: 25,
    lifespanYears: 80,
    nativeRegion: 'Tropical coastal regions',
    careTips: 'Full sun, sandy well-drained soil. Regular watering. Thrives in tropical climates.',
    category: 'palm',
    icon: '🥥',
  },
  {
    id: 'date-palm',
    commonName: 'Date Palm',
    scientificName: 'Phoenix dactylifera',
    co2PerYear: 7,
    co2YoungMultiplier: 0.2,
    growthRate: 'slow',
    maxHeightM: 21,
    lifespanYears: 100,
    nativeRegion: 'Middle East, North Africa',
    careTips: 'Full sun, well-drained soil. Drought tolerant. Needs low humidity.',
    category: 'palm',
    icon: '🌴',
  },
  {
    id: 'birch',
    commonName: 'Silver Birch',
    scientificName: 'Betula pendula',
    co2PerYear: 14,
    co2YoungMultiplier: 0.4,
    growthRate: 'fast',
    maxHeightM: 20,
    lifespanYears: 80,
    nativeRegion: 'Europe, Northern Asia',
    careTips: 'Full sun, moist well-drained soil. Attractive bark. Prune in summer to avoid sap bleed.',
    category: 'deciduous',
    icon: '🌲',
  },
  {
    id: 'willow',
    commonName: 'Weeping Willow',
    scientificName: 'Salix babylonica',
    co2PerYear: 20,
    co2YoungMultiplier: 0.5,
    growthRate: 'fast',
    maxHeightM: 15,
    lifespanYears: 50,
    nativeRegion: 'China',
    careTips: 'Full sun, moist soil near water. Fast growing – plant near ponds or streams.',
    category: 'deciduous',
    icon: '🌿',
  },
  {
    id: 'lemon',
    commonName: 'Lemon',
    scientificName: 'Citrus limon',
    co2PerYear: 7,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 6,
    lifespanYears: 50,
    nativeRegion: 'Asia',
    careTips: 'Full sun, well-drained soil. Water regularly, avoid waterlogging. Fertilize monthly.',
    category: 'fruit',
    icon: '🍋',
  },
  {
    id: 'fig',
    commonName: 'Fig',
    scientificName: 'Ficus carica',
    co2PerYear: 11,
    co2YoungMultiplier: 0.35,
    growthRate: 'medium',
    maxHeightM: 10,
    lifespanYears: 70,
    nativeRegion: 'Middle East, Mediterranean',
    careTips: 'Full sun, well-drained soil. Drought tolerant once established. Prune after harvest.',
    category: 'fruit',
    icon: '🪴',
  },
  {
    id: 'teak',
    commonName: 'Teak',
    scientificName: 'Tectona grandis',
    co2PerYear: 28,
    co2YoungMultiplier: 0.4,
    growthRate: 'fast',
    maxHeightM: 40,
    lifespanYears: 200,
    nativeRegion: 'South and Southeast Asia',
    careTips: 'Full sun, deep well-drained soil. Thrives in seasonal climates with distinct dry season.',
    category: 'deciduous',
    icon: '🌳',
  },
  {
    id: 'cedar',
    commonName: 'Cedar',
    scientificName: 'Cedrus libani',
    co2PerYear: 23,
    co2YoungMultiplier: 0.25,
    growthRate: 'slow',
    maxHeightM: 40,
    lifespanYears: 1000,
    nativeRegion: 'Middle East, Mediterranean',
    careTips: 'Full sun, well-drained soil. Drought tolerant. Iconic pyramidal shape when young.',
    category: 'evergreen',
    icon: '🌲',
  },
  {
    id: 'jacaranda',
    commonName: 'Jacaranda',
    scientificName: 'Jacaranda mimosifolia',
    co2PerYear: 16,
    co2YoungMultiplier: 0.35,
    growthRate: 'medium',
    maxHeightM: 15,
    lifespanYears: 100,
    nativeRegion: 'South America',
    careTips: 'Full sun, well-drained soil. Stunning purple flowers in spring. Frost sensitive.',
    category: 'flowering',
    icon: '💜',
  },
  {
    id: 'magnolia',
    commonName: 'Magnolia',
    scientificName: 'Magnolia grandiflora',
    co2PerYear: 14,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 15,
    lifespanYears: 100,
    nativeRegion: 'North America',
    careTips: 'Full sun to partial shade, moist acidic soil. Stunning large white flowers.',
    category: 'flowering',
    icon: '🌸',
  },
  {
    id: 'cherry-blossom',
    commonName: 'Cherry Blossom',
    scientificName: 'Prunus serrulata',
    co2PerYear: 9,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 12,
    lifespanYears: 50,
    nativeRegion: 'Japan, Korea, China',
    careTips: 'Full sun, moist well-drained soil. Iconic spring blooms. Prune immediately after flowering.',
    category: 'flowering',
    icon: '🌸',
  },
  {
    id: 'bamboo',
    commonName: 'Bamboo',
    scientificName: 'Phyllostachys aurea',
    co2PerYear: 40,
    co2YoungMultiplier: 0.6,
    growthRate: 'fast',
    maxHeightM: 15,
    lifespanYears: 40,
    nativeRegion: 'Asia',
    careTips: 'Full sun to partial shade. Control spreading with rhizome barriers. Excellent carbon sequester.',
    category: 'evergreen',
    icon: '🎋',
  },
  {
    id: 'olive',
    commonName: 'Olive',
    scientificName: 'Olea europaea',
    co2PerYear: 9,
    co2YoungMultiplier: 0.2,
    growthRate: 'slow',
    maxHeightM: 10,
    lifespanYears: 2000,
    nativeRegion: 'Mediterranean',
    careTips: 'Full sun, well-drained alkaline soil. Extremely drought tolerant. Prune to open canopy.',
    category: 'fruit',
    icon: '🫒',
  },
  {
    id: 'guava',
    commonName: 'Guava',
    scientificName: 'Psidium guajava',
    co2PerYear: 13,
    co2YoungMultiplier: 0.4,
    growthRate: 'fast',
    maxHeightM: 8,
    lifespanYears: 40,
    nativeRegion: 'Central and South America',
    careTips: 'Full sun, tolerates poor soil. Water regularly. Heavy producer once established.',
    category: 'fruit',
    icon: '🍈',
  },
  {
    id: 'acacia',
    commonName: 'Acacia',
    scientificName: 'Acacia nilotica',
    co2PerYear: 18,
    co2YoungMultiplier: 0.45,
    growthRate: 'fast',
    maxHeightM: 20,
    lifespanYears: 100,
    nativeRegion: 'Africa, South Asia',
    careTips: 'Full sun, drought tolerant. Excellent nitrogen fixer. Great for arid regions.',
    category: 'deciduous',
    icon: '🌳',
  },
  {
    id: 'spruce',
    commonName: 'Norway Spruce',
    scientificName: 'Picea abies',
    co2PerYear: 19,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 55,
    lifespanYears: 300,
    nativeRegion: 'Europe',
    careTips: 'Full sun, moist well-drained soil. Classic Christmas tree shape. Very cold hardy.',
    category: 'evergreen',
    icon: '🎄',
  },
  {
    id: 'arjuna',
    commonName: 'Arjuna',
    scientificName: 'Terminalia arjuna',
    co2PerYear: 24,
    co2YoungMultiplier: 0.4,
    growthRate: 'fast',
    maxHeightM: 25,
    lifespanYears: 200,
    nativeRegion: 'South Asia',
    careTips: 'Full sun, moist riverine soil. Medicinal bark. Excellent shade tree.',
    category: 'deciduous',
    icon: '🌳',
  },
  {
    id: 'peepal',
    commonName: 'Peepal / Sacred Fig',
    scientificName: 'Ficus religiosa',
    co2PerYear: 26,
    co2YoungMultiplier: 0.35,
    growthRate: 'fast',
    maxHeightM: 30,
    lifespanYears: 3000,
    nativeRegion: 'South Asia',
    careTips: 'Full sun, tolerates varied soils. Releases oxygen at night. Sacred in many traditions.',
    category: 'deciduous',
    icon: '🌳',
  },
  {
    id: 'tulip-tree',
    commonName: 'Tulip Tree',
    scientificName: 'Liriodendron tulipifera',
    co2PerYear: 21,
    co2YoungMultiplier: 0.4,
    growthRate: 'fast',
    maxHeightM: 35,
    lifespanYears: 200,
    nativeRegion: 'North America',
    careTips: 'Full sun, moist deep soil. Stunning tulip-shaped flowers. Excellent street tree.',
    category: 'flowering',
    icon: '🌷',
  },
  {
    id: 'moringa',
    commonName: 'Moringa / Drumstick',
    scientificName: 'Moringa oleifera',
    co2PerYear: 12,
    co2YoungMultiplier: 0.5,
    growthRate: 'fast',
    maxHeightM: 12,
    lifespanYears: 30,
    nativeRegion: 'South Asia',
    careTips: 'Full sun, well-drained soil. Drought tolerant, nutrient-rich leaves. Multipurpose tree.',
    category: 'deciduous',
    icon: '🌿',
  },
  {
    id: 'pomegranate',
    commonName: 'Pomegranate',
    scientificName: 'Punica granatum',
    co2PerYear: 8,
    co2YoungMultiplier: 0.3,
    growthRate: 'medium',
    maxHeightM: 6,
    lifespanYears: 200,
    nativeRegion: 'Middle East, South Asia',
    careTips: 'Full sun, well-drained soil. Drought tolerant. Beautiful flowers and nutritious fruit.',
    category: 'fruit',
    icon: '🍎',
  },
];
